org: jwala

service: task-manager-api

provider:
  name: aws
  runtime: nodejs24.x
  region: ap-south-1

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [tasksTable, Arn]

  httpApi:
    authorizers:
      myAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: 
          Fn::Join:
            - ""
            - - "https://cognito-idp.ap-south-1.amazonaws.com/"
              - Ref: UserPool
        audience:
          - Ref: usersClient
        


functions:
  createTask:
    handler: handler.createTask
    events:
      - httpApi:
          path: /tasks
          method: post
          authorizer:
            name: myAuthorizer

resources:
  Resources:
    tasksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TasksTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - KeyType: HASH
            AttributeName: id

        BillingMode: PAY_PER_REQUEST

    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: TaskManagerUserPool

    usersClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: TaskManagerUserClient
        UserPoolId: 
          Ref: UserPool



